Slice2
chingu-voyage3/toucans-20 pull request #26
Opened 2017-12-22 15:50 UTC by Al3x4

2017-12-22 15:52 UTC, Al3x4 commented
@andrzejp   you had a button with id cta-button. I changed that id into a class so I can use the class for the button in slice 2.  I hope that's ok.

2017-12-23 14:57 UTC, AndrzejProchyra requested changes
That's great! I've made a small suggestion and we need to work out how to make the pictures in the next section overlap with the background.

2017-12-23 14:57 UTC, andrzejp commented on styles/main.css
>  }
I would suggest adding `background-size: 100% auto;` here to let the background stretch to the full width on viewports larger than 1680px.

2017-12-23 16:54 UTC, Al3x4 commented
I fixed the background width issue. 

I also reordered the styles int he CSS file so they're in order of slices. ]

the pull request has been automatically updated.

2017-12-23 19:45 UTC, andrzejp commented on styles/main.css
> +}
Oops! An extraneous brace. This stops the next rule from being applied!

2017-12-23 19:46 UTC, AndrzejProchyra requested changes
This is good. There's an extraneous brace though that needs to be removed.

2017-12-26 18:17 UTC, Al3x4 commented
Okie dokie, fixed the extra bracket. should all be fine now.. wanna have a look?

2017-12-27 12:09 UTC, AndrzejProchyra approved these changes

2017-12-27 12:10 UTC, merged

2017-12-27 12:10 UTC, andrzejp commented
There's something odd going on with vertical spacing but this is good for now!